### ISSUE TITLE
Renew base year should not be year of application

### ISSUE THREAD

**Issue by marthabmd** [dchealthlink/DCHBX_PL-SQL_Code_To_Extract_Curam_Data#2]
Renew base year is not the same as year of application, so the pull needs to use the renew base year data element.

This needs to be fixed in pull that will be used to produce APTC for final eligibility renewals, therefore, ideally fixed in the next week or so.

**Comment by pegasus4848** [comment]
After overcoming difficulties with compiling the (large) procedure get_integrated_case_by_caseref (the existence of a table on UAT, which does not exist on PreProd (DCASLCLUAT_SOAINFRA.xref_subscriber): 
SELECT DISTINCT
                   p.personid AS person_id,
                   p.concernroleid AS concern_role_id,
                   x.dcas_01 AS hbx_person_id
              FROM dchxpersonmapping p, **DCASLCLUAT_SOAINFRA.xref_subscriber** x
             WHERE p.personid = x.crm_01

I used consentForIRSRenewals, which contains the renewal_base_year value, which had to be extended to include month and day (January 01) to avoid a formatting error.
